### PR TITLE
fixes for g2 boxes

### PR DESCRIPTION
**Pull request by ksimuk**

### CODE REVIEW

**Comment by ghost** [comment]
1.5 Challenge... complete challenge and it passes OK but the dir and file contents does not show even after resync file tree (close guides and confirmed)
folders

**Comment by ksimuk** [comment]
ready to check again

**Comment by ghost** [comment]
A: 2.Practical uses of the > utility. Screenshot of contents of file-list.txt differs to actual content of file
practical uses of
B: 3. 1. Content concatenation. File tree still open to project-log directory, should be to workspace so users can see and open hello.txt and hi.txt as instructed
content
C; 4.2 Challenge. Challenge does not pass (using solution given)
4_2challenge

**Comment by ksimuk** [comment]
> A: 2.Practical uses of the > utility. Screenshot of contents of file-list.txt differs to actual content of file

Are you sure you executed the right command? looks like you executed just `ls > file-list.txt`

> B: 3. 1. Content concatenation. File tree still open to project-log directory, should be to workspace so users can see and open hello.txt and hi.txt as instructed

fixed, was broken in the original

>  C; 4.2 Challenge. Challenge does not pass (using solution given)

works for me
image

**Pull request merged**
